<?php

/**
 * @file
 * Install, update and uninstall functions for the Custom Tests module.
 */

/**
 * Implements hook_schema().
 */
function testsuite_schema() {
  if (\Drupal::database()->schema()->tableExists('custom_test_item')) {
    \Drupal::database()->truncate('custom_test_item')->execute();
    \Drupal::database()->schema()->dropTable('custom_test_item');
  }

  $schema['custom_test_item'] = [
    'description' => 'Stores the custom test items.',
    'fields' => [
      'id' => [
        'description' => 'The ID of this item',
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
      'test' => [
        'description' => 'The test name',
        'type' => 'varchar',
        'length' => 180,
        'not null' => TRUE,
      ],
      'module' => [
        'description' => 'The module',
        'type' => 'varchar',
        'length' => 180,
        'not null' => TRUE,
      ],
      'name' => [
        'description' => 'The test name',
        'type' => 'varchar',
        'length' => 180,
        'not null' => TRUE,
      ],
      'description' => [
        'description' => 'The test description',
        'type' => 'text',
        'not null' => TRUE,
      ],
      'report' => [
        'description' => 'The error reported',
        'type' => 'text',
        'not null' => TRUE,
      ],
      'created' => [
        'description' => 'A timestamp indicating when the item was created',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
    ],
    'indexes' => [
      'indexing' => ['id', 'created'],
    ],
    'primary key' => ['id'],
  ];

  return $schema;
}

/**
 * Implements hook_uninstall().
 */
function testsuite_uninstall() {
  if (\Drupal::database()->schema()->tableExists('custom_test_item')) {
    \Drupal::database()->truncate('custom_test_item')->execute();
    \Drupal::database()->schema()->dropTable('custom_test_item');
  }

  // Delete sessions.
  if (\Drupal::request()->hasSession()) {
    \Drupal::request()->getSession()->remove('custom_tests_overview_filter');
  }

  // Delete config in key values.
  \Drupal::keyValue("system.schema")->delete("testsuite");
}
